제품 상세 정보 조회 기능구현
wecode-bootcamp-korea/33-2nd-CREAM-backend pull request #7
Opened 2022-06-14 14:31 UTC by stresszero

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 제품 상세 정보 조회 기능구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 제품 상세 정보 조회를 위한 View 추가
- aggregate를 이용하여 즉시판매가, 즉시구매가를 조회
- 프론트엔드 요구사항에 맞게 가격, 시간정보 포매팅
- 테스트 코드 추가

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- aggregate의 사용법에 대해 배웠습니다.

<br />

## :: 기타 질문 및 특이 사항
- 없음

2022-06-15 06:45 UTC, lordmyshepherd requested changes

2022-06-15 06:45 UTC, lordmyshepherd commented on products/views.py
> +class ProductDetailGraphView(View):
order/views.py로 옮겨주세요.

```python
# bids app에서 관리해 주세요.
class OrderListView(View):
    # order?product_id=1&start_date=""&end_date=""
    # products/1/orders?start_date=""&end_date=""

    def get(self, request, product_id):
        start_date = request.GET.get("")
        end_date   = request.GET.get("")

        orders = Order.objects.filter(product_size__product_id=product_id).order_by('-created_at')

        results = [{
            'id'         : order.id,
            'size'       : order.product_size.size.name,
            'price'      : int(order.price),
            'created_at' : order.created_at.strftime('%y/%m/%d')
        } for order in orders]

        return JsonResponse({'orders': results}, status=200)
```

2022-06-15 06:45 UTC, lordmyshepherd commented on products/tests.py
> +    def test_success_get_product_detail_graph(self):
fail case 추가해주세요~

2022-06-15 06:45 UTC, lordmyshepherd commented on products/tests.py
> +    def test_success_get_product_detail_graph(self):
fail case 추가해주세요~

2022-06-15 06:45 UTC, lordmyshepherd commented on products/tests.py
> +    def test_success_get_product_detail(self):
여기도 fail까지는 작성 부탁드립니다!

2022-06-15 06:45 UTC, lordmyshepherd commented on products/tests.py
> +    def test_success_get_product_detail(self):
여기도 fail까지는 작성 부탁드립니다!

2022-06-15 06:45 UTC, lordmyshepherd commented on products/views.py
> +            product = Product.objects.get(id=product_id)
```python
# bids app에서 관리해 주세요.
class OrderListView(View):
    # order?product_id=1&start_date=""&end_date=""
    # products/1/orders?start_date=""&end_date=""

    def get(self, request, product_id):
        start_date = request.GET.get("")
        end_date   = request.GET.get("")

        orders = Order.objects.filter(product_size__product_id=product_id).order_by('-created_at')

        results = [{
            'id'         : order.id,
            'size'       : order.product_size.size.name,
            'price'      : int(order.price),
            'created_at' : order.created_at.strftime('%y/%m/%d')
        } for order in orders]

        return JsonResponse({'orders': results}, status=200)
```

2022-06-15 06:45 UTC, lordmyshepherd commented on products/views.py
> +            product = Product.objects.get(id=product_id)
```python
            product = Product.objects.annotate(
                buy_now_price  = Min("productsize__bids__price", filter=Q(productsize__bids__type_id=BidTypeEnum.SELL.value)),
                sell_now_price = Max("productsize__bids__price", filter=Q(productsize__bids__type_id=BidTypeEnum.BUY.value)),
            ).get(id=product_id)
            
            order = Order.objects.filter(product_size__product_id=product_id).order_by('-created_at')
            recent_price = format(int(order.first().price), ',d') if order.exists() else "최근 거래 없음"

```

2022-06-15 11:37 UTC, stresszero commented on products/views.py
> +class ProductDetailGraphView(View):
리뷰해주신대로 수정했습니다

2022-06-15 11:37 UTC, stresszero commented on products/views.py
> +            product = Product.objects.get(id=product_id)
리뷰해주신대로 수정했습니다

2022-06-15 11:38 UTC, stresszero commented on products/views.py
> +            product = Product.objects.get(id=product_id)
리뷰해주신대로 수정했습니다

2022-06-15 12:00 UTC, stresszero commented on products/tests.py
> +    def test_success_get_product_detail_graph(self):
리뷰해주신대로 수정했습니다.

2022-06-15 12:00 UTC, stresszero commented on products/tests.py
> +    def test_success_get_product_detail(self):
리뷰해주신대로 수정했습니다.

2022-06-15 12:00 UTC, stresszero commented on products/tests.py
> +    def test_success_get_product_detail(self):
리뷰해주신대로 수정했습니다.

2022-06-15 13:36 UTC, stresszero commented on products/tests.py
> +    def test_success_get_product_detail_graph(self):
리뷰해주신대로 수정했습니다

2022-06-16 04:49 UTC, autoboy4commit commented on products/views.py
> +            q &= Q(category_id=category_id)
> 사이즈 필터링을 하기 위한 q &= Q(sizes__name__in=shoe_size_list)와 q &= Q(sizes__id__in=shoe_size_ids)의 성능 차이가 있는지 궁금합니다. 둘다 더블 언더바(___) lookup을 사용하는것은 동일한데 name 조건과 id조건에 있어서 차이점이 있을까요?

좋은 질문 주셔서 감사합니다 세영님!
logging을 사용해서 query가 어떻게 작성되는지 직접 확인해보시면 아시겠지만 category 같은 경우는 product table과 정참조 관계에 있기 때문에 직접 category_id로 조회 할 경우 table join이 줄어드는 것을 볼 수 있습니다.

다만 말씀 주신 것처럼 size table 같은경우 역참조 관계에 있기 때문에 logging을 통해 확인 시 query 상으로도 똑같이 join이 일어나는 것을 볼 수 있습니다.

그럼에도 name보다 id로 조회 해야하는것의 이유는 고유한 값인 id와 달리 name은 언제든지 바뀔 수 있는 값이기 때문입니다.

2022-06-16 05:03 UTC, stresszero commented on products/views.py
> +            q &= Q(category_id=category_id)
답변 감사합니다.😄

2022-06-16 05:33 UTC, autoboy4commit commented
LGTM 🚀

2022-06-16 05:33 UTC, merged